### ISSUE TITLE
Request - toggles for allow{Global,Default,Managed,DNS}

### ISSUE THREAD

**Issue by laduke** [erikh/ztui#2]
I toggle allowGlobal a lot lately from testing stuff. `zerotier-cli set <networkId> allowDefault=1` is a pain. 👍

**Comment by erikh** [comment]
ok, could have a flag toggles key that lets you adjust flags in a secondary step, e.g. `f` then `d` adjusts "allowDNS"

**Comment by erikh** [comment]
this is resolved in latest main, will go out in 0.2.0
