### ISSUE TITLE
Cannot escape help screen

### ISSUE THREAD

**Issue by micush** [erikh/ztui#4]
Hi,

I'm on Ubuntu 22.04. If I press "h" for the help screen and then press "Esc" the help screen does not go away and I have to close the terminal to proceed. Tried on v0.1.4.

**Comment by raku-cat** [comment]
Can confirm this happens for me as well on arch linux using the latest binary from releases.

**Comment by erikh** [comment]
Sorry, I have been away from the computer for some time. I will attempt to look at this next week. Please ping me if you do not hear from me in a week. My sincerest apologies for being so slow.

**Comment by csc-chicken** [comment]
it's still not fixed
let me fork and check

**Comment by csc-chicken** [comment]
I think I found the solution. Here you added an OK() at the last of the function , maybe remove it solve it
![圖片](https://user-images.githubusercontent.com/66060998/236121877-19c09563-8937-4620-99a5-477e29b09b68.png)

**Comment by erikh** [comment]
Thanks! I literally ran into this issue earlier this week playing around with it. I'll give it a shot in a bit and see if your suggestion changes anything.

You're also welcome to submit a pull request.

------- Original Message -------

**Comment by erikh** [comment]
I just fixed this, it will be committed shortly, it will be closed, and I'll cut 0.1.5.

Thanks for the report!

------- Original Message -------

**Comment by csc-chicken** [comment]
Haha I don't know how to use rust. I just found the workflow really weird. display_dialogs has Ok() at the end and in dialog_help() Ok() appeared twice, which means Ok() will run twice in display_dialogs when help dialog is showed. Really weird haha

**Comment by csc-chicken** [comment]
@erikh  And I haven't pull request after github use token to verify. Maybe I have to relearn.

**Comment by erikh** [comment]
it's already fixed. In short, that wasn't the issue.

------- Original Message -------

**Comment by csc-chicken** [comment]
@erikh Nevermind .Glad we fix it together

**Comment by csc-chicken** [comment]
![圖片](https://user-images.githubusercontent.com/66060998/236129116-d33517f7-55db-4355-8b2e-6950848a1e21.png)
Oh! I see!

**Comment by erikh** [comment]
yep, it wasn't trapping the help dialog screen to allow these commands to come through.

Glad we fixed it together, too! :)

------- Original Message -------
